### ISSUE TITLE
jnlp pod error when creating

### ISSUE THREAD

**Issue by emelianrus** [jenkinsci/docker-jnlp-slave#105]
hi, could you please help with that ?
`Error: Could not find or load main class hudson.remoting.jnlp.Main`
Pod couldn't start completely after latest update to 3.35-1

**Comment by oleg-nenashev** [comment]
I am working on it: https://github.com/jenkinsci/docker-slave/releases/tag/3.35-2 . It should take about 1 hour to get new versions released

**Comment by emelianrus** [comment]
Great, thanks a lot

**Comment by oleg-nenashev** [comment]
3.35-2 has been released. Alpine and JDK11 images are waiting in the Build Queue
https://github.com/jenkinsci/docker-jnlp-slave/releases/tag/3.35-2
