### ISSUE TITLE
Jenkins agent version is still 3.29 in Alpine and JDK11

### ISSUE THREAD

**Issue by eran-davidi-optibus** [jenkinsci/docker-jnlp-slave#119]
Can you please update this to version 3.35 as jenkinsci/docker-slave repository

The master image was updated but the slaves are on 3.29 which makes them offline

This is critical

**Comment by oleg-nenashev** [comment]
It is likely related to https://github.com/jenkinsci/docker-slave/pull/84 which is my mistake during reviews. Which image do you use @eran-davidi-optibus ?

CC @alxsap

**Comment by eran-davidi-optibus** [comment]
3.35-4-alpine

**Comment by alxsap** [comment]
@oleg-nenashev https://github.com/jenkinsci/docker-jnlp-slave/pull/118 is also ready for review and release. It consumes the released changes from https://github.com/jenkinsci/docker-slave/pull/84

**Comment by oleg-nenashev** [comment]
Released https://github.com/jenkinsci/docker-jnlp-slave/releases/tag/3.35-5 . Thanks @alxsap !
