### ISSUE TITLE
Latest alpine dockerhub image

### ISSUE THREAD

**Issue by alxsap** [jenkinsci/docker-jnlp-slave#125]
On [Dockerhub](https://hub.docker.com/r/jenkinsci/jnlp-slave/tags) there is a latest `3.35-5` image but the latest alpine image is `3.35-2-alpine`.

Could you please release a `3.35-5-alpine` image as well? Thanks

**Comment by oleg-nenashev** [comment]
Looks like I broke DockerHub again:(

**Comment by alxsap** [comment]
It is available now: https://hub.docker.com/r/jenkins/jnlp-slave/tags
Thanks, @oleg-nenashev
