### ISSUE TITLE
Error starting ECS slaves

### ISSUE THREAD

**Issue by jicomusic** [jenkinsci/docker-jnlp-slave#13]
When running a Jenkins slave (jenkinsci/jnlp-slave) as a container on ECS, the task stops immediately.  The logs show the following: 
two arguments required, but got []
java -jar slave.jar [options...] <secret key> <slave name>
 -cert VAL                       : Specify additional X.509 encoded PEM
                                   certificates to trust when connecting to
                                   Jenkins root URLs. If starting with @ then
                                   the remainder is assumed to be the name of
                                   the certificate file to read.
 -credentials USER:PASSWORD      : HTTP BASIC AUTH header to pass in for making
                                   HTTP requests.
 -headless                       : Run in headless mode, without GUI
 -jar-cache DIR                  : Cache directory that stores jar files sent
                                   from the master
 -noreconnect                    : If the connection ends, don't retry and just
                                   exit.
 -proxyCredentials USER:PASSWORD : HTTP BASIC AUTH header to pass in for making
                                   HTTP authenticated proxy requests.
 -tunnel HOST:PORT               : Connect to the specified host and port,
                                   instead of connecting directly to Jenkins.
                                   Useful when connection to Hudson needs to be
                                   tunneled. Can be also HOST: or :PORT, in
                                   which case the missing portion will be
                                   auto-configured like the default behavior
 -url URL                        : Specify the Jenkins root URLs to connect to.

I have the URL listed as an environment variable with the URL of the Jenkins master as its value.  Do I need to specify the url in the entrypoint?

**Comment by ndeloof** [comment]
as explained on README you need to run this image as:
`docker run jenkinsci/jnlp-slave -url http://jenkins-server:port <secret> <slave name>`

can replace url with environment variable `JENKINS_URL` but need to pass slave's secret token and name.

**Comment by ndeloof** [comment]
Are you using amazone-ecs-slaves plugin ?

**Comment by jicomusic** [comment]
Yes, I'm using the ECS slaves plug-in.  Ideally, I would like to use the jnlp-slave container to build Docker images.  I was able to fix the earlier problem I was having by using a fixed port (Jenkins Global Security Settings).

**Comment by CICDSimplified** [comment]
i am facing the same issue. I have configured all required values in ecs plugin, the tunnel as HOST:PORT, alternate JENKINS_URL, but still it is not connecting. Kindly help me.

**Comment by sathish97625** [comment]
hi, I am facing the same issue, can you help me here, thanks
