### ISSUE TITLE
Is it necessary to VOLUME the jenkins home dir?

### ISSUE THREAD

**Issue by staffan-einarsson** [jenkinsci/docker-jnlp-slave#14]
Hi,

Is it really necessary to mark the jenkins user home dir as a VOLUME in the Dockerfile? If not, I would prefer it to be something I can do in my own deriving image. Right now this is blocking me from chowning and chmodding files that I COPY into the home dir (like ssh keys) in my own Dockerfile. Since the VOLUME comes before, such changes are discarded.

**Comment by oleg-nenashev** [comment]
I assume it's for JAR cache, which is being stored in home dir now.
Should be fixed/broken by https://issues.jenkins-ci.org/browse/JENKINS-18578 in remoting 3

**Comment by staffan-einarsson** [comment]
Thanks. Wouldn't it be enough then to mark `/home/jenkins/.jenkins` as a volume?

**Comment by oleg-nenashev** [comment]
@carlossg WDYT?

**Comment by carlossg** [comment]
@oleg-nenashev is the jenkins slave copying data only to ~/.jenkins ? then it makes sense to use that as a volume, or nothing at all

**Comment by oleg-nenashev** [comment]
@carlossg Jenkins slave itself should not use other directories in home dir. I'm not sure about Jenkins core's logic and plugins hooking on it

**Comment by staffan-einarsson** [comment]
Great! Thanks @carlossg

**Comment by ndeloof** [comment]
workspace is created in `/jenkins/home`, not inside `~/.jenkins`, so I had to revert this.

**Comment by ndeloof** [comment]
@staffan-einarsson any reason you don't use jenkins credentials support to manage ssh keys ? Should not need to customize slave's $HOME.

**Comment by ndeloof** [comment]
@staffan-einarsson I'd like to revert this. Not making HOME a volume means workspace isn't created on a volume, .m2, .npm and others won't get cached, etc.

**Comment by carlossg** [comment]
I think you can still put it in a volume, it's just the user responsibility to do it

**Comment by ndeloof** [comment]
You indeed can run the image and force `/home/jenkins` to be a volume, but as a result will have two volumes, one for `/home/jenkins` and one for `/home/jenkins/.jenkins`,  which doesn't make much sense imo.

**Comment by carlossg** [comment]
I mean if we remove the volume definition and make it user's responsibility to deal with volumes

**Comment by ndeloof** [comment]
@carlossg yes indeed, image doesn't need to declare a volume, end-user can just run with `-v slaveroot:/home/jenkins`. Initial content from image will then be copied into this volume. 
This would just require end-user to know this path should be a volume, so have to make it clear in documentation.

**Comment by staffan-einarsson** [comment]
Sorry for late follow up. @ndeloof For my specific case it I was using a plugin that did integrate with Jenkins credentials and having user SSH keys was a valid work-around. More generally, a lot of environment config goes in the home dir so it is not unreasonable to want to be able to set it up when building the image.

Yes, I agree. It would be better to leave the decision of whether to make it a volume to the user. It sounds like persisting caches is the main argument, as an optimization. I could equally see the use case that you want to wipe the caches between starts to make sure you have a clean starting point.

**Comment by ndeloof** [comment]
@staffan-einarsson the main argument is not about persisting jar cache - this one could not be persisted. The main argument is about persisting slave root to persist workspaces and tool installations, so you can retrieve them on next build.

Environment configuration should not live in slave $HOME but rely on Jenkins mechanism to inject configuration.

**Comment by jniemin** [comment]
@ndeloof Seems that latest version of image was not created based on jenkinsci/slave that had this change. I did run docker inspect for both latest from repo and results were following

jenkinsci/slave:latest
"Created": "2016-09-14T09:31:24.487360509Z"
"Volumes": { "/home/jenkins/.jenkins": {} }

jenkinsci/jnlp-slave:latest
"Created": "2016-09-14T09:02:01.065000398Z"
"Volumes": { "/home/jenkins": {} }

So if you use jnlp-slave as base image you will still have volume pointin to /home/jenkins/ not /home/jenkins/.jenkins

**Comment by dcw329** [comment]
+1. Having this issue. Still need this fixed. for now i am creating my own jenkins slaves FROM openjdk:8-jdk-alpine. Id really like to be able to go back to the community jenkins

**Comment by ndeloof** [comment]
This introduces a regression in docker-slaves-plugin as the workspace is not available from other containers in the build environment
