### ISSUE TITLE
Jenkins Slave : Root directory not writable.

### ISSUE THREAD

**Issue by theobolo** [jenkinsci/docker-jnlp-slave#15]
Hello everyone, 

I tried to use the automatic Slave deployment with my Kubernetes cluster and my Jenkins Master, but i face a problem when the Slave is provisioning : 

Here the logs of the pod : 

```
2016-09-05T11:54:31.771124775Z Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
2016-09-05T11:54:31.972612022Z Sep 05, 2016 11:54:31 AM hudson.remoting.jnlp.Main createEngine
2016-09-05T11:54:31.972635623Z INFO: Setting up slave: jnlp-slave-a7265a22a0820
2016-09-05T11:54:31.974522204Z Sep 05, 2016 11:54:31 AM hudson.remoting.jnlp.Main$CuiListener <init>
2016-09-05T11:54:31.974535404Z INFO: Jenkins agent is running in headless mode.
2016-09-05T11:54:31.984373826Z Exception in thread "main" java.lang.RuntimeException: Root directory not writable
2016-09-05T11:54:31.984453230Z 	at hudson.remoting.FileSystemJarCache.<init>(FileSystemJarCache.java:44)
2016-09-05T11:54:31.984472631Z 	at hudson.remoting.Engine.<init>(Engine.java:139)
2016-09-05T11:54:31.984497832Z 	at hudson.remoting.jnlp.Main.createEngine(Main.java:164)
2016-09-05T11:54:31.984520933Z 	at hudson.remoting.jnlp.Main.main(Main.java:148)
2016-09-05T11:54:31.984544634Z 	at hudson.remoting.jnlp.Main._main(Main.java:144)
2016-09-05T11:54:31.984568535Z 	at hudson.remoting.jnlp.Main.main(Main.java:110)
```

I tried with the slaves in Privileged mode = true and some other stuff but still not working, if someone have an idea :)

Théo

**Comment by theobolo** [comment]
Adding Jenkins master screenshot : 

![lol](https://cloud.githubusercontent.com/assets/7281773/18247645/e819ff0c-7373-11e6-8d17-5526bb128bb4.png)

And Kubernetes dashboard screenshot : 

![lolilol](https://cloud.githubusercontent.com/assets/7281773/18247665/02e84000-7374-11e6-8360-9fd0dfb931a9.png)

**Comment by alon-argus** [comment]
Just happened to me as well. Changing slave image tag to `2.62` (instead of `latest`) has fixed the issue for now.

**Comment by theobolo** [comment]
@alon-argus really thanks ;) that's worked for me too, i'm letting the issue opened, maybe to fix the latest tag.

Cheers

**Comment by mrceresa** [comment]
Dear all,
I'm also experiencing this, with the latest image available:
```
$ sudo kubectl logs jnpl-slave-13a44d8d6093c --namespace=jenkins
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
Nov 11, 2016 5:02:08 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: jnpl-slave-13a44d8d6093c
Nov 11, 2016 5:02:08 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Exception in thread "main" java.lang.RuntimeException: Root directory not writable
	at hudson.remoting.FileSystemJarCache.<init>(FileSystemJarCache.java:44)
	at hudson.remoting.Engine.<init>(Engine.java:139)
	at hudson.remoting.jnlp.Main.createEngine(Main.java:164)
	at hudson.remoting.jnlp.Main.main(Main.java:148)
	at hudson.remoting.jnlp.Main._main(Main.java:144)
	at hudson.remoting.jnlp.Main.main(Main.java:110)
```

 However, if I run from the command line a container manually it works:
```
node$ sudo docker run -ti docker.io/jenkinsci/jnlp-slave:latest /bin/bash
pod$ java -jar /usr/share/jenkins/slave.jar -jnlpUrl http://10.254.151.87/computer/slave1/slave-agent.jnlp
...
INFO: Connected
```

Any idea on how to investigate that further?

Best,

Mario

**Comment by ndeloof** [comment]
Kubernetes has a weird way to handle volumes...

**Comment by ndeloof** [comment]
@mrceresa I guess this is caused by https://github.com/kubernetes/kubernetes/issues/2630

**Comment by mrceresa** [comment]
Hello @ndeloof ! 
Thanks for your prompt response and for the link. I was reading the thread and trying to figure out a possible fix but I'm still not sure what to do: should I add a security context like this?
```
    securityContext:
        fsGroup: 10000
```
Or simply force the creation of the volume with 0777?
If it is the the former, how do I convince the kubernetes plugins of jenkins to use the fsGroup? 
If it is the latter, I suppose that means I should rebuild the image: but then the fact that you didn't add the fix yourself suggests that maybe you tried it and it didn't work...

By the way, I'm curious, what changes between the manual invocation (which works) and the one done by jenkins plugins (that shows the permission error)?

Thanks a lot for any hints you might provide!

Mario

**Comment by ndeloof** [comment]
@mrceresa when you run it manually you use plain docker, which handle the volume permission right. When you ask kubernetes to manage the volume, it just create a root-owned volume. I consider this a bug in kubernetes implementation of volumes. There's nothing we can do from this image.

**Comment by mrceresa** [comment]
Thanks @ndeloof, @carlossg for your help with this.
I see that there is no more activity on kubernetes/kubernetes#2630 after they suggested to use the fsgroup directive. Do you think that would fix the problem? If so is there a place where we can put configure it in the jenkins pluings?
Or should I give up on the idea of dinamicaly provision the containers and have them as standard slaves always on?

Best,

Mario

**Comment by ndeloof** [comment]
kubernetes plugin used to work without any extra hack afaik. @carlossg could give you some guidance here. IIRC he's traveling for now

**Comment by carlossg** [comment]
fsgroup is the right way to do it, if it doesn't work with the kubernetes plugin , please open an issue there

**Comment by kennethrithvik** [comment]
@mrceresa @carlossg How can i set the fsgroup configuration in the jenkins-kubernetes plugin

**Comment by nehaljwani** [comment]
If someone faced the same issue after upgrading kubernetes-plugin, please read the [changelog](https://github.com/jenkinsci/kubernetes-plugin/blame/6d6083d9f70701662ca466232fb735d42689b158/CHANGELOG.md#L11).

**Comment by larruda** [comment]
@nehaljwani it took me a whole day of work to find this message and solve that issue. Thanks a lot for bringing this to our attention. It should be much better documented, also things like this are just awful. Thanks again!

**Comment by oleg-nenashev** [comment]
@larruda Do you expect any changes in this Docker image or documentation? Not sure about that, seems to be issue with Kubernetes plugin

**Comment by larruda** [comment]
@oleg-nenashev you're totally right! Please don't worry about it, just wanted to thank the fellow guy here for this information he gave which otherwise would be very difficult to find.

**Comment by nehaljwani** [comment]
@larruda Indeed, I found it the hard way too, but turns out that after someone reported this at https://issues.jenkins-ci.org/browse/JENKINS-40847 , it was documented in the README with this patch: https://github.com/jenkinsci/kubernetes-plugin/commit/8849676cf1c334506361244917ec9af02bc516f4

**Comment by cmoulliard** [comment]
> fsgroup is the right way to do it

When I set the user to the container spec, then it works

```
    securityContext:
      runAsUser: 1000
```

Question:
How can we pass @carlossg  this securityContact parameter to the ContainerTemplate of the jenkins kubernetes plugin ?

**Comment by solomenvAbhishek** [comment]
hi..can any one help me with this ...please

while launching an agent on the Linux machine facing an error

ERROR: Unexpected error in launching a slave. This is probably a bug in Jenkins.
java.lang.RuntimeException: Root directory not writable: /home/jenkins/.jenkins/cache/jars
	at hudson.remoting.FileSystemJarCache.<init>(FileSystemJarCache.java:57)
	at hudson.remoting.JarCache.getDefault(JarCache.java:32)
	at hudson.remoting.Channel.<init>(Channel.java:520)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:323)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:389)
	at hudson.plugins.sshslaves.SSHLauncher.startSlave(SSHLauncher.java:1074)
	at hudson.plugins.sshslaves.SSHLauncher.access$500(SSHLauncher.java:145)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:818)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:793)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[09/12/17 10:15:09] Launch failed - cleaning up connection
[09/12/17 10:15:09] [SSH] Connection closed...


it shows for different linux box too ...please help me

**Comment by mpechner** [comment]
I am not using kubernetes.  I am using an AWS EC2 instance

**Comment by karthik-ir** [comment]
I'm facing the same issue, What is the workaround on this ?

**Comment by dgonzalezruiz** [comment]
For the records, the working directory is cleaned up in the slaves everytime they are spun up. Therefore, even if you have any custom image that creates folder under such working directory (in my case, I set it up to `/home/jenkins`), it will be deleted. Be careful with that!

**Comment by MadeInChina** [comment]
+1
```
version: '2'
services:
  jenkinsci-slave5:
    image: jenkinsci/jnlp-slave
    environment:
      JENKINS_AGENT_NAME: jenkins-slave
      JENKINS_SECRET: fac1f848bf46d90440979a3e9914f5e412b49b7ebf1fe0adc4bfa2ad2fcd349b
      JENKINS_URL: master
    volumes:
    - /home/jenkins/slave-1-home:/home/jenkins
    - /home/jenkins/m2/repository:/home/.m2/repository
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: alway
```
Got Root directory not writable: /home/jenkins/.jenkins/cache/jars

**Comment by ndeloof** [comment]
as you use a bind mount for /home/jenkins it's up to you to manage permissions there.
aka : bind mount is evil, don't use it

**Comment by henshitou** [comment]
> @nehaljwani it took me a whole day of work to find this message and solve that issue. Thanks a lot for bringing this to our attention. It should be much better documented, also things like this are just awful. Thanks again!

Hello, high appreciate it if you could share how can you solve this issue?
