### ISSUE TITLE
Repository description still links to old image

### ISSUE THREAD

**Issue by jnsdrtlf** [jenkinsci/docker-jnlp-slave#151]
According to the warning

> ❗️  Warning! This image used to be published as jenkinsci/jnlp-slave. That image name is deprecated, use jenkins/jnlp-slave.

jenkins**ci**/jnlp-slave is deprecated. However, the description of this repository still links to **jenkinsci** instead of **jenkins**.

**Comment by oleg-nenashev** [comment]
Sorry for missing this issue. It is fixed now, thanks!
