### ISSUE TITLE
Jenkins agent fails to start

### ISSUE THREAD

**Issue by dhawal55** [jenkinsci/docker-jnlp-slave#16]
I'm new to Jenkins and trying to troubleshoot an issue where our Jenkins agent fails to start. Error: `Error: Could not find or load main class hudson.remoting.jnlp.Main`

We are running:
Jenkins master version: 2.22
Jenkins jnlp slave version: 2.90

Any idea why my agents stopped working? The only change i did is upgrade from 2.20 to 2.22

**Comment by dhawal55** [comment]
I rolled back to 2.20 but still getting the same error.

**Comment by dhawal55** [comment]
duh!! I also changed the jnlp slave version from 2.60 to 2.90. Rolling it back to 2.60 works.

**Comment by carlossg** [comment]
what commands are you running and how are you running them?

**Comment by damianmadeira** [comment]
tengo el mismo problema

**Comment by oleg-nenashev** [comment]
I doubt commenting in a 3-year-old PR will help. Please consider creating a new issue and listing your versions at least
