### ISSUE TITLE
Connect to Jenkins Server Using Self Signed Certificate

### ISSUE THREAD

**Issue by will-sterling** [jenkinsci/docker-jnlp-slave#17]
Our Jenkins server uses a self signed certificate and the docker image is refusing to connect.  I've added "-noCertificateCheck" to the JVM arguments field in the system configuration of the Amazon EC2 container service plug-in but it does not seem to be getting used by the container.  How should I be passing this option to the container?

**Comment by diffalot** [comment]
i had a similar problem trying to use a letsencrypt certificate for my jenkins master, and i wasn't able to get the `noCertificateCheck` to work even when modifying the `jenkins-slave` script, so I downloaded the .der format "Let’s Encrypt Authority X3 (IdenTrust cross-signed)" certificate from https://letsencrypt.org/certificates/ and added it to the openjdk keystore.  You can do something similar in your dockerfile with your self signed certificate:

```
USER root
ADD lets-encrypt.der .
RUN keytool -importcert -alias local-CA \
  -keystore /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/security/cacerts \
  -file lets-encrypt.der \
  -storepass changeit
USER jenkins

ENTRYPOINT ["jenkins-slave"]
```

Note that you probably have your self signed cert in pem format, and java needs it in der format, so something like `openssl x509 -outform der -in certificate.pem -out certificate.der` may come in handy

**Comment by carlossg** [comment]
I guess that is more a question for the EC2 container service plug-in, you can ask in the jenkins users mailing list

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/docker-jnlp-slave/releases/tag/3.35-5 likely resolves it by adding support of headless connection and explicit env vars for certificates & Co. Please reopen the issue if it does not flly resolve the issue

**Comment by alikbm** [comment]
@diffalot tried it and it works, thanks

**Comment by felipecrs** [comment]
> https://github.com/jenkinsci/docker-jnlp-slave/releases/tag/3.35-5 likely resolves it by adding support of headless connection and explicit env vars for certificates & Co. Please reopen the issue if it does not flly resolve the issue

I don't understand. How does that solves the issue? How to set a custom certificate?
