### ISSUE TITLE
Can't automatically connect the container back to Jenkins

### ISSUE THREAD

**Issue by Reifier** [jenkinsci/docker-jnlp-slave#20]
I am currently experiencing this issue: http://stackoverflow.com/questions/41253094/kubernetes-plugin-containers-cant-connect-back-to-jenkins 

Can you guys point me in the right direction?

**Comment by Reifier** [comment]
Ended up writing a custom script to go around the issue.

**Comment by spunkedy** [comment]
What script did you use if you don't mind sharing?

**Comment by Reifier** [comment]
@Spunkley 
I don't think I have it on me any longer, but I used the script in entry point to accept the arguments I have passed with Jenkins like jnlp.mac and the other one. So when container starts it actually kicks off by utilizing these arguments and then proceeds to do the intended jobs.

**Comment by Reifier** [comment]
@Spunkedy ^

Sorry posting from phone. Can't edit previous comment.

**Comment by spunkedy** [comment]
haha, thanks! Yeah, I might add in an arg so that if the master dies out, it stays up
