### ISSUE TITLE
how to run docker commands and aws cli scripts in ECS slave node

### ISSUE THREAD

**Issue by rajasekaran07** [jenkinsci/docker-jnlp-slave#21]
Hi Team,

I am trying to run docker commands and aws cli scripts in my ecs slave nodes but by default it is not configured. Can someone suggest how to achieve this.

--raja

**Comment by israel-santiago-praxis** [comment]
Estarei de férias entre os dias 11/01/2017 até o dia 31/01/2017. 

Caso precise de algo que não possa aguardar meu retorno, gentileza entrar em contato através do email "atendimento@praxis.com.br" ou telefone (31)3273-2861 que a equipe Praxis terá o prazer em atendê-los.
 
Atenciosamente, 
Gustavo Ferreira Coimbra e Silva

(Este é um e-mail automático, favor não responder)

**Comment by carlossg** [comment]
For questions please ask in the Jenkins mailing lists https://jenkins-ci.org/content/mailing-lists
