### ISSUE TITLE
Docker hub image needs to be updated with more recent version of the upstream image jenkinsci/slave

### ISSUE THREAD

**Issue by tmiller** [jenkinsci/docker-jnlp-slave#22]
Looking on docker hub I was wondering why the home directory on the `jenkinsci/jnlp-slave` image was a volume instead of `/home/jenkins/.jenkins`. I looked into it and it seems the current image on docker hub is using an older version of `jenkinsci/slave`.

It appears that `jenkinsci/slave` was updated roughly 30 minutes after `jenkins/jnlp-slave`. This caused jenkins/jnlp-slave to not receive the updates from `jenkinsci/slave`
https://hub.docker.com/r/jenkinsci/jnlp-slave/builds/bbiwdakzwehkc7vvtuhpbaw/
https://hub.docker.com/r/jenkinsci/slave/builds/bnkls23k5zz4tmwaykdqap6/

**Comment by carlossg** [comment]
I think @ndeloof can set it up to rebuild `latest` on `jenkinsci/jnlp-slave` changes

**Comment by slavakl** [comment]
Current latest is the subject to this issue https://github.com/docker-library/openjdk/issues/96
Basically, if you do apt-get dist-upgrade, java is removed.

**Comment by ndeloof** [comment]
https://hub.docker.com/r/jenkins/docker-jnlp-slave/ is configured with automated builds

**Comment by slavakl** [comment]
@ndeloof that's great. Your latest image on docker hub is still 6 months old, though.  And still doesn't use new jenkinsci/slave image, that has java certificates issue fixed. In order to really close this issue, could you please trigger your automatic update? Should as easy as version increase.

**Comment by ndeloof** [comment]
@slavakl I've been asking we manage docker images as classic CI builds to build & push docker images on ci.jenkins.io. Automated builds unfortunately don't give us control on what / when things are built.

**Comment by slavakl** [comment]
Where should we report an issue to have it built?

**Comment by oleg-nenashev** [comment]
It is somewhat configurable in DockerHb according to the explanation from @DamienDuportal. I have requested access to DockerHub image settings in [INFRA-1104](https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-1104). Once I get the access, I will try to configure a workaround there.

But I agree with @ndeloof that the best solution is  to have a Jenkins-powered CI/CD on jenkins.io. At least for Testing purposes.

**Comment by oleg-nenashev** [comment]
The version is released, DockerHub automatic builds will be picking the latest versions of https://hub.docker.com/r/jenkinsci/slave/ now
