### ISSUE TITLE
User access right inconsistency

### ISSUE THREAD

**Issue by akranga** [jenkinsci/docker-jnlp-slave#23]
jenkinsci/jenkins creates `jenkins` user with: `gid=1000` and `uid=1000`. Jenkins slave declares user `with uid=10000`. `jenkins:jnlp-slave` creates user with `adduser -S -h $HOME jenkins jenkins`

All these makes difficult to reuse artifacts generated by job executed on master (like `checkout` step)  by slave that operates with different uid/gid and shares the same workspace.

I would like to propose move migrate slaves under unified user `jenkins:jenkins` with same` uid` and `gid`

**Comment by carlossg** [comment]
how do you share master and slave workspace?

**Comment by akranga** [comment]
With NFS volume

**Comment by carlossg** [comment]
you would need to use the -u options to run as non root, plus some extra configurations
https://blog.csanchez.org/2017/01/31/running-docker-containers-as-non-root/
