### ISSUE TITLE
Feature Request: Env variables for secret and slave name

### ISSUE THREAD

**Issue by lafraia** [jenkinsci/docker-jnlp-slave#3]
Like `JENKINS_URL` it should be possible to specify `SLAVE_SECRET` and `SLAVE_NAME`. This should make it easier to provision slave templates and avoid mistakes with entrypoint and command.

**Comment by SantoDE** [comment]
I'd like that idea! I dont get this to run currently, based on the fact that I cant pass that both arguments within docker-compose. Or at least I dont know how @lafraia

**Comment by frangarcia** [comment]
Do you know by any chance where can I find the secret for the slave? I don't find it anywhere.

**Comment by SantoDE** [comment]
Hey @frangarcia, sure!

- Create the node (=Slave) on your jenkins (please make sure to select "Launch slave agents via Java Web Start)
- On the Node Overview Page, click the node you just created
- You'll find a line 
> Run from slave command line: java -jar slave.jar -jnlpUrl https://XXX/computer/jlnp%20test%20node/slave-agent.jnlp -secret 69730fe577d3892269f19a3b700e50d090f034020386461a8dc08fd43b7ed26b

**Comment by frangarcia** [comment]
Thanks @SantoDE!

I used to find it there but there wasn't there anymore and the problem was I had the anonymous user with agent connect capabilities, so the secret was not even needed, so it wasn't being shown.

**Comment by s332401890** [comment]
Launch slave agents via Java Web Start, i cannot find this choice,i on the node page i just get 
`java -jar slave.jar -jnlpUrl http://10.185.235.87:8080/jenkins/computer/slave1/slave-agent.jnlp` 
Jenkins ver. 2.19.1

**Comment by s332401890** [comment]
but in 2.19.3 is OK, WTF!

**Comment by carlossg** [comment]
PR #24 should enable this
