### ISSUE TITLE
Bug: arguments are doubled

### ISSUE THREAD

**Issue by alonl** [jenkinsci/docker-jnlp-slave#31]
When I run the slave as I always used to do it (using Kubernetes plugin) - it passes these arguments to the command: 
`${computer.jnlpmac} ${computer.name}`

Now, using the latest jnlp-slave version, I get this error:

`two arguments required, but got [${computer.jnlpmac}, ${computer.name},${computer.jnlpmac}, ${computer.name}]`
(the arguments are doubled)

Current workaround that solves it:

I explicitly set JENKINS_SECRET and JENKINS_NAME environment variables to be empty.

**Comment by thefron** [comment]
Having the same issue, spawning slave pods up until it hits container cap.

**Comment by oleg-nenashev** [comment]
So it has been caused by #24 from @carlossg. Who is also a maintainer of Kubernetes. The most straightforward way would be to skip parameters if the Env Vars are specified, but it needs ack from @carlossg . I am not sure which use-cases he had in mind

**Comment by carlossg** [comment]
I didn't expect people would pass both args and env vars, so I guess it needs to check for that and use only args in that case

**Comment by oleg-nenashev** [comment]
@carlossg Yes, this is also my hotfix plan. Will you be able to implement it and test with your Kubernetes stuff?

**Comment by alonl** [comment]
> I didn't expect people would pass both args and env vars, so I guess it needs to check for that and use only args in that case

It happens even when I define no env vars.

**Comment by TGippert** [comment]
It's hard to say what is the"root cause". a) the kubernetes plugin which adds args AND env variables or b) the jnlp-slave!?
Currently, when using the kubernetes plugin, I have to explicitly add "containerTemplate(name: 'jnlp', image: 'jenkinsci/jnlp-slave:2.62-alpine', args: '${computer.jnlpmac} ${computer.name}')" to my podTemplate.

The OLD jenkinsci/jnlp-slave:2.62-alpine ist still working.

Does anybody has a better workaround?

**Comment by oleg-nenashev** [comment]
Seems @carlossg is not available to fix that. Doing it on my own.

**Comment by themalkolm** [comment]
@TGippert we started having this issue after the docker image got updated I believe. We solved it the same way you described: just freezing docker image version. Not sure there is a better workaround.

**Comment by oleg-nenashev** [comment]
Created the pull request: #33

**Comment by oleg-nenashev** [comment]
Both `latest` and `alpine` images have been updated, please confirm the fix works for you

**Comment by TGippert** [comment]
Great job! Thanks :+1: 

`containerTemplate(name: 'jnlp', image: 'jenkinsci/jnlp-slave:alpine', args: '${computer.jnlpmac} ${computer.name}', alwaysPullImage: true)`
writes the following into the output of the jnlp agent:
Warning: SECRET is defined twice in command-line arguments and the environment variable
Warning: AGENT_NAME is defined twice in command-line arguments and the environment variable

So I decided to use the containerTemplate without args
`containerTemplate(name: 'jnlp', image: 'jenkinsci/jnlp-slave:alpine', alwaysPullImage: true)`

**Comment by oleg-nenashev** [comment]
@TGippert warnings are "as designed" from this repo PoV, because it is generally not an expected configuration.

@carlossg will still need to triangulate and fix the issue on the Kubernetes plugin side

**Comment by thefron** [comment]
@oleg-nenashev confirmed working.

I had to add `jnlp` `containerTemplate` to my `podTemplate` with `alwaysPullImage: true` since my k8s cluster has cached old `alpine` image.

**Comment by oleg-nenashev** [comment]
@thefron Will add more tags as a part of #30

**Comment by arno01** [comment]
Since Google pointed me here and others might come as well, the ``jenkinsci/jnlp-slave`` has been deprecated now. You need to use ``jenkins/jnlp-slave:<tag>``, where tag can be either: alpine (88MB) or latest (296MB). https://hub.docker.com/r/jenkins/jnlp-slave/tags/
