### ISSUE TITLE
Failed to write to /home/jenkins/.jenkins

### ISSUE THREAD

**Issue by cilindrox** [jenkinsci/docker-jnlp-slave#32]
I've set up a Jenkins master on GKE along with the Kubernetes plugin however, I keep hitting a `java.io.IOException: Failed to write to /home/jenkins/.jenkins/cache/jars/F2/84FCC8C54FBFD68EF9E319A863DC13.jar` error whenever a new slave is created by the plugin.

Using the image `jenkinsci/jnlp-slave` with an `Always pull` setting.
Master image is `jenkinsci/jenkins:2.46.1-alpine`

I've tried setting `_JAVA_OPTIONS` to `-Duser.home=/tmp`, unsuccessfully.

Any help is appreciated.

PS: I've ran into #31 , which I worked around by unsetting both `JENKINS_NAME` and `JENKINS_SECRET` and passing `${computer.jnlpmac} ${computer.name}` as build args to the slave.

**Comment by oleg-nenashev** [comment]
Unfortunately Remoting JAR cache should be always in Home Directory, and I doubt user.home can be changed so easily. It is tracked as https://issues.jenkins-ci.org/browse/JENKINS-18578, I hope to fix it soon.

Do you use any external volumes for homedir? CC @carlossg

**Comment by cilindrox** [comment]
@oleg-nenashev not mounting anything on the slaves

Looks like the issue is no longer present with the `latest` image from Docker hub. Closing this.

**Comment by peterwiebe** [comment]
I also ran into the same `Failed to write` error as @cilindrox, I am adding the `latest` tag to the jnlp image to see if it works

**Comment by somayajulas** [comment]
I also ran into the same Failed to write error as @cilindrox, and Yes my docker container use my home directory as an external volume (i.e., the home directory mounted on a NFS mount). The NFS mount where my home directory was mounted does have lot of disk space. 

Having home directory as NFS mount cause this issue?

**Comment by cilindrox** [comment]
@somashekar10 I'm currently using `jenkins/jnlp-slave:3.16-1-alpine` for the agents. Try checking the permissions for your particular mount and UID for the proc
