### ISSUE TITLE
Docker client in jnlp slave

### ISSUE THREAD

**Issue by radu-matei** [jenkinsci/docker-jnlp-slave#35]
Hi, everyone!

Assuming I use this exact image I only get an environment with JDK, right? What if I want to build other types of projects? Or more specifically, when configuring the image for the slave I cannot have multiple images and configure the pipeline to use a specific slave.

So what is the accepted way of building multiple types of projects, considering the following:

 - I don't want to change the slave image often
 - I don't want to explicitly install all stuff (Go, Ruby or Node) in the same container?

The obvious way to handle this is to [have Docker inside the slave, as described in this article](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) and mount `/var/run/docker.sock` into the container.

I did this and [you can find the resulting Dockerfile here (I also put `kubectl`)](https://radu-matei.github.io/blog/kubernetes-jenkins-azure/#the-docker-image-for-the-slaves), GitHub repo [here](https://github.com/radu-matei/jenkins-slave-docker/blob/master/Dockerfile).

The question I have is: apart from this method, is there any other that allows me to build whatever project I want without modifying the slave?

Thanks,
Radu M

**Comment by oleg-nenashev** [comment]
> Assuming I use this exact image I only get an environment with JDK, right? What if I want to build other types of projects? 

You can create your own image on the top of this image.

> So what is the accepted way of building multiple types of projects...

If you have images for other tools including the tool you need and JDK, you can use multiple images within your build flow by using Jenkins Pipeline and shared workspaces. Useful plugins: Docker Pipleline Plugin, External Workspace Manager Plugin

**Comment by radu-matei** [comment]
> You can create your own image on the top of this image.

Yes, I know I can build images on top of this base image, but the idea is that for every project I want to build I have to create a new image, then configure a separate pipeline (with a new Docker image I have to manage) - which I don't really want to do and seems a bit overkill.

I understand this is the way of doing right now, but how about the approach I suggested above? Is this something we might want to use? (at least from the simplicity point of view?)

Thanks!

**Comment by radu-matei** [comment]
Based on this approach I wrote this article that tries to better explain how to achieve what I was trying to say - [article here](https://radu-matei.github.io/blog/kubernetes-jenkins-azure/#configuring-jenkins-to-dinamically-spawn-agents-docker-containers-for-builds).

**Comment by carlossg** [comment]
the kubernetes plugin allows now multi-container agents, so you can reuse the images from the hub without needing to extend this one. I think that covers the use case you are mentioning

**Comment by radu-matei** [comment]
Yes, the example you provided covers the use case I exemplified.
Closing this. Thanks!
