### ISSUE TITLE
The jnlp container in each slave consumes about 200M memories

### ISSUE THREAD

**Issue by tianya2010** [jenkinsci/docker-jnlp-slave#42]
We used the jenkins-kubernetes plugin to set up a test framework, and we found that the jnlp-container in each jenkins slave consumes about 200M memories. Is it normal or there is something wrong?

Is there any way to constrain the memory consumption? Will such limit affects the performance?

**Comment by oleg-nenashev** [comment]
200M is an expected consumption if Java starts with the default options. You can tweak Java options and try to decrease the memory footprint, but I am not sure it's possible to achieve much difference

**Comment by tianya2010** [comment]
Thanks for the suggestion. 

The jnlp container is started by jenkins-kubernetes plugin by default, and how can I tweak the java options for this container instead of other affect the other working containers in a slave?

**Comment by oleg-nenashev** [comment]
It makes sense to as Kubernetes maintainers. @carlossg fyi

**Comment by carlossg** [comment]
You can see how to customize it at https://github.com/jenkinsci/kubernetes-plugin#pipeline-support
