### ISSUE TITLE
how to pass JVM options ?

### ISSUE THREAD

**Issue by alice0706** [jenkinsci/docker-jnlp-slave#60]
if i want pass JVM options when creating slave node on jenkins master ?

**Comment by mtricolici** [comment]
it seams that it ignores 'JAVA_OPTS'

```
podTemplate(
    label: podLabel,
    containers: [
        containerTemplate(
            name: 'jnlp',
            image: 'jenkins/jnlp-slave:latest',
            alwaysPullImage: true,
            ttyEnabled: true,
            command: 'jenkins-slave',
            workingDir: '/home/jenkins',
            resourceRequestCpu: '50m',
            resourceRequestMemory: '512Mi',
            resourceLimitMemory: '512Mi',
            envVars: [
              containerEnvVar(key: 'JAVA_OPTS', value: '-Xmx256M -Xms256M -Djava.awt.headless=true')
            ]
        ),
        containerTemplate(...
```

**Comment by oleg-nenashev** [comment]
> if i want pass JVM options when creating slave node on jenkins master ?

If you are talking about the Web UI, these JVM args are really used if and only if you start the agent from Java Web Start. These options are not passed to JNLP agents in any other way.

> it seams that it ignores 'JAVA_OPTS'

I would suggest asking @carlossg about that. It should support JAVA_OPTS if the standard entrypoint is used. Not wure about the K8s plugin

**Comment by carlossg** [comment]
it should work in k8s plugin. If it doesn't, open a issue in jira https://issues.jenkins-ci.org/projects/JENKINS/issues
