### ISSUE TITLE
Jenkins JNLP Agent Docker image on top of of another docker image

### ISSUE THREAD

**Issue by IKOBH** [jenkinsci/docker-jnlp-slave#61]
Hi.

I'm trying to build agents for testing my project on different os platforms (Ubuntu, RH etc) using Jenkins JNLP Agent Docker image.

To do so I want to built a container for each os platform that runs Jenkins JNLP Agent. Thus I need to create a dockerfile for each os, that also runs JNLP Agent on top of it.

Since Jenkins JNLP Agent dockerfile contains the COPY cmd, I can't combine two dockerfiles (e.g ubuntu & JNLP Agent dockerfiles).

Any suggestions how to do that?
Could you be kind to publish a more robust dockerfile for JNLP Agent?

Many thanks

**Comment by henshitou** [comment]
@IKOBH do you find a solution to resolve your issue? could you please share your solution? thanks.

**Comment by krichter722** [comment]
This is the way Docker works. You can suggest improvement there. This can be closed as there's nothing that Jenkins JNLP slave can do.
