### ISSUE TITLE
Root access for provisioning this container 

### ISSUE THREAD

**Issue by AlexandrSemak** [jenkinsci/docker-jnlp-slave#63]
Hi,
I try to use this container via Jenkins kubernetes-plugin and faced with issus that i have not root access to install directly what i need.
How can i overcome it? Because i wont use this container as base.

**Comment by angusmf** [comment]
Hi! The docker stuff for Jenkins sets the current user to 'jenkins' at some point. You can set it back. In your docker file, add a line:
USER root

**Comment by AlexandrSemak** [comment]
For this need rebuild docker file, I won't do it

**Comment by AlexandrSemak** [comment]
I try use pod template for create pod with security content via yaml

**Comment by oleg-nenashev** [comment]
@AlexandrSemak this container is using `jenkins` as a default user, no plans to change that. You can start the container with another user if the K8s plugin supports it. Or, alternatively, you can create your own image as suggested above.

I doubt there is something else we can do in this request. This image won't be running as root by default.

**Comment by carlossg** [comment]
in k8s you can set `runAsUser` https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
