### ISSUE TITLE
Broken ps -p with jenkins 2.135 and alpine image

### ISSUE THREAD

**Issue by robinro** [jenkinsci/docker-jnlp-slave#65]
We are running the  3.19-1-alpine version and after the jenkins upgrade from 2.134 to 2.135 our builds started failing with this message:
```
Running shell script
ps: unrecognized option: p
BusyBox v1.27.2 (2018-06-06 09:08:44 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
```
Adding `apk add procps` to the jnlp-slave image fixed the issue. Maybe this should be part of the published image?
I couldn't find the place where `ps -p` is called, though. It might also be in one of the plugins, like jenkins-kubernetes.

**Comment by TAvardit** [comment]
Hi @robinro , I saw the same issue since yesterday when I upgraded our Jenkins plugins in our test environment. I isolated the issue to upgrading of Durable Task from 1.22 to 1.23. (https://plugins.jenkins.io/durable-task) . Downgrading back to 1.22 solve the issue for us.

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/docker-slave/pull/28 has been integrated, the automatic build will pick it soon for the `alpine` tag
