### ISSUE TITLE
Several builds on one agent

### ISSUE THREAD

**Issue by paszczak3** [jenkinsci/docker-jnlp-slave#74]
Hi :) Is there possibility to lunch several builds on one agent? When I want to run a few builds I get that "node are not available" and when first build is finished next build is starting.  I would like to create several builds. I created 2 project for tests and run these project at the same time but one of them was waiting till another finished its job(Then could not use the same agent).

**Comment by carlossg** [comment]
questions to jenkins-user mailing list please
