### ISSUE TITLE
Wrong UID on jenkins/jnlp-slave:latest-jdk11 image

### ISSUE THREAD

**Issue by tomasyany** [jenkinsci/docker-jnlp-slave#77]
The `jenkins/jnlp-slave:latest-jdk11` seems to have been built with the `jenkins/slave:3.27-1` image from https://hub.docker.com/r/jenkins/slave.

(A quick `echo $UID` will show `10000` and not the new value of `1000` (see https://github.com/jenkinsci/docker-slave/pull/43/files).)

Shouldn't the `jenkins/jnlp-slave:latest-jdk11` image been built with the `jenkins/slave:latest-jdk11` image, hence have the `1000` UID for the default `jenkins` user?

The way I checked:
```
$ docker run -it jenkins/jnlp-slave:latest-jdk11 /bin/bash
jenkins:~$ echo $UID
10000
jenkins:~$ exit
$ docker run -it jenkins/slave:latest-jdk11 /bin/bash
jenkins:~$ echo $UID
1000
jenkins:~$ exit
```

**Comment by vinixavier** [comment]
+1

**Comment by micw** [comment]
Having predictable user ids is a very important thing, especially when using k8s where a jenkins build pod is composed from more than one container. Having 1000 is very common here, 10000 seems only to be used by the jnln-agent. I think it should be 1000!

**Comment by tomasyany** [comment]
> Having predictable user ids is a very important thing, especially when using k8s where a jenkins build pod is composed from more than one container. Having 1000 is very common here, 10000 seems only to be used by the jnlp-agent. I think it should be 1000!
> 
> Edit: same with the jdk8 version.

Definitely! But my main point was that the image should have been built based on the correct image (according to names), not a different one. If not, it's super misleading.

**Comment by micw** [comment]
The UUID was changed from 10000 to 1000 ~3 months ago: 
https://github.com/jenkinsci/docker-slave/commit/19215a4806cf1a90c0991cf44f72db373f19e869

Looks like the "latest" jdk11 build is based on a tagged (older) version of the jenkins slave image:
https://github.com/jenkinsci/docker-jnlp-slave/blob/jdk11/Dockerfile#L23

Same for the master (=latest) and alpine images.

**Comment by micw** [comment]
So the fix is to let the "latest" images be based on the "latest" patent images.

**Comment by oleg-nenashev** [comment]
We had some unfortunate race conditions, on DockerHub, and that's why it was fixed. I agree it makes sense to revert it

**Comment by micw** [comment]
You should enable the parent->child trigger (if not yet done), so that the image is triggered if the parent is updated.

**Comment by oleg-nenashev** [comment]
The trigger *was* enabled.It was a part of the stability issue we had.

Anywqy, I merged all PRs. Thanks @micw
