### ISSUE TITLE
OpenJDK 12 version ?

### ISSUE THREAD

**Issue by f-ld** [jenkinsci/docker-jnlp-slave#88]
OpenJDK 12 is out.
Last image tag is still JDK 11.

Would it be possible to create an openjdk 12 version ?

**Comment by oleg-nenashev** [comment]
Hi. Jenkins project does not support Java 12 right now, only Java 8 and Java 11 are supported (see [JEP-211](https://github.com/jenkinsci/jep/tree/master/jep/211)). Right now there is no coordinated effort to support Java 12 in @jenkinsci/sig-platform 

CC @jenkinsci/java11-support just in case

**Comment by f-ld** [comment]
Ok, I understand that Jenkins cannot run with Java 12.
But how feasible would it be to have a slave that can run jobs using Java 12? (i.e. have more than one Java installed on the image so that jobs can select a different java?).

I haven't been thinking it much and maybe you already know the potentials problems one would face trying it?

**Comment by oleg-nenashev** [comment]
There will be no problems with that as long as you run Jenkins runtime (including agent) on Java 11. You can run builds with another Java version by properly configuring environment and tools. You can find an example for such configuration and demos in https://github.com/jenkinsci/ci.jenkins.io-runner. E.g. https://github.com/jenkinsci/ci.jenkins.io-runner/blob/master/init_scripts/src/main/groovy/Tools.groovy

**Comment by oleg-nenashev** [comment]
ftr https://jenkins.io/doc/administration/requirements/java/#executing-jobs-on-jenkins
