### ISSUE TITLE
Deprecated docker hub more updated than recommend one

### ISSUE THREAD

**Issue by iskigow** [jenkinsci/docker-jnlp-slave#93]
Recently, the new JDK 11 version docker image was released and with `jenkins/slave:latest-jdk11` updated I saw that Deprecated docker hub of `jnlp-slave` received the updated and the recommend one no.

![Screenshot_1](https://user-images.githubusercontent.com/30843/62468080-27ddbf80-b763-11e9-949a-6be2e16486c6.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/30843/62468107-362bdb80-b763-11e9-8e26-03af581c1b72.jpg)

Do you have any plans to upgrade to the recommended version?

And wouldn't it be better not to update the deprecated version anymore?

**Comment by oleg-nenashev** [comment]
Personally I want to completely rebuild the agent packaging logic.
Currently it is pretty difficult to maintain images up to date

**Comment by markyjackson-taulia** [comment]
I have been working to refactor this (albeit a bit slower then I want to)

**Comment by oleg-nenashev** [comment]
We could start from replicating https://github.com/jenkinsci/docker-slave

**Comment by oleg-nenashev** [comment]
FTR I filed the PRs to update to 3.35 releases

**Comment by oleg-nenashev** [comment]
Should he fixed in 3.35-5
