### ISSUE TITLE
Q: adding dotnet runtime to the base jnlp-slave

### ISSUE THREAD

**Issue by grahamehorner** [jenkinsci/docker-jnlp-slave#96]
we are attempting to add the dotnet core runtime to the a jnlp-slave docker image, but we are having issues where the symlink to the dotnet executable is not found? is there an official/supported Jenkins-slave that has the dotnet core runtime installed? or information around how this can be achieved?

thanks in advance

**Comment by oleg-nenashev** [comment]
There is no official image for .NET ATM. The recommendation is to extend one of the existing images.

The image could be also contributed to https://github.com/jenkinsci/jnlp-agents . Maybe @slide would be also willing to add .NET runtime to the official Docker images he is working on

**Comment by slide** [comment]
I would recommend looking at jenkinsci/jnlp-agents for examples on how to combine multiple images 5o achieve what you want.

**Comment by grahamehorner** [comment]
@slide @oleg-nenashev we at DXC technology are looking to create a set of jenkins slave docker images for the community; these will be for all versions of .net core both runtime & sdk; at present we have these in our internal repo; we will hopefully be publishing these to the DXC technology org for public access; and it would be good IMHO if these ended up with an official jenkin slave under your org

**Comment by StephenDryden** [comment]
@slide @oleg-nenashev I have create a PR to add dotnet core runtime 2.2 and 3.0 jnlp agents.

https://github.com/jenkinsci/jnlp-agents/pull/10

**Comment by slide** [comment]
This was merged into the jnlp-agents repo, so closing out.
